### ISSUE TITLE
Create better strategy for arc string animation

### ISSUE THREAD

**Issue by light-layer** [light-layer/light-layer.github.io#8]
Ensure that the starting position of the end of the song list string is the same for song lists of any length.

**Comment by sgogos1** [comment]
Fixed the issue with needing to find the right percentage in order to see the whole arc. Arc now moves from right to left (start to end of text)

Beginning of the text starts ("from" attribute of animate) on the right side of the arc (startOffset=100%) and a percentage is generated based on the length of the text and the number of characters for one arc (roughly 143) so that the "to" attribute of the animate element has a auto-calculated percentage based on the length of the text.
